### ISSUE TITLE
Log file naming and piping for jobs

### ISSUE THREAD

**Issue by JoshuaUrrutia** [tapis-project/tapis-jobs#31]
currently, jobs output both std out and std err logs to a single file tapisjob.out 

I'd like to make a feature request to split these outputs into separate .out and .err files.
Also, I'd like to request the ability to redefine the name of these files with support for the `${JobUUID}` macro, so that the log files will include the jobUUID for posterity.

**Comment by JoshuaUrrutia** [comment]
The log renaming/splitting doesn't seem to be working.
The app def accepts the log config, the job is submitted with the log config, the log config show up in tapisjob.sh and tapisjob.env but there's still a single output log (`tapisjob.out`, defined in the slurm script).
Ex. a2cps tenant, job `d4f5e307-2c93-4263-82b5-f6d4e96c7e78-007`

app.json/job.json
```
"jobAttributes"
...
    "parameterSet"
    ....
            "logConfig": {
                "stdoutFilename": "${JobUUID}.out",
                "stderrFilename": "${JobUUID}.err"
            }
```
tapis.env:
```
export _tapisStderrFilename=${JobUUID}.err
export _tapisStdoutFilename=${JobUUID}.out
```
tapisjob.sh 
```
,_tapisStderrFilename="${JobUUID}.err",_tapisStdoutFilename="${JobUUID}.out",
```
I'd also expect the macro to have populated in tapisjob.sh and tapisjob.env (that seems to be the case for other places $JobUUID is defined, like the `_tapisArchiveSystemDir` in this job.

**Comment by richcar58** [comment]
Running in DEV and STAGING; deployed to PROD as hotfix3.
