### ISSUE TITLE
Unable to use different execSystem in job even when execSystems are shared

### ISSUE THREAD

**Issue by chandra-tacc** [tapis-project/tapis-jobs#61]
####  Repro Steps:

1. Setup two systems (frontera, ls6) which are shared publicly.
2. create an app with execSystem set to frontera. Publish the app and share publicly
3. Submit a job with the app (from step 2) and the execSystem set to ls6.

**Result :** 

Job executes and fails with the following error:

JOBS_WORKER_PROCESSING_ERROR An exception occurred on JobWorker wkr-DefaultQueue-39 on queue tapis.jobq.submit.DefaultQueue running wkr-DefaultQueue-JobQueueProcessor while processing job a8da9125-b873-47e8-9185-e60fd31e9c02-007: Cannot invoke "java.util.List.contains(Object)" because "this._sharedAppCtxAttribs" is null

**Expected Result:**
Adding an already shared exec system in job submission should work.

**Comment by scblack321** [comment]
Stack trace from log:

> 2023-12-08 20:15:32.309 ERROR [wkr-DefaultQueue-39/fFSv] e.u.t.t.j.worker.JobQueueProcessor:186 - JOBS_WORKER_PROCESSING_ERROR An exception occurred on JobWorker wkr-DefaultQueue-39 on queue tapis.jobq.submit.DefaultQueue running wkr-DefaultQueue-JobQueueProcessor while processing job a8da9125-b873-47e8-9185-e60fd31e9c02-007: Cannot invoke "java.util.List.contains(Object)" because "this._sharedAppCtxAttribs" is null
> edu.utexas.tacc.tapis.shared.exceptions.TapisException: Cannot invoke "java.util.List.contains(Object)" because "this._sharedAppCtxAttribs" is null
>         at edu.utexas.tacc.tapis.shared.utils.TapisUtils.tapisify(TapisUtils.java:746)
>         at edu.utexas.tacc.tapis.jobs.utils.JobUtils.tapisify(JobUtils.java:79)
>         at edu.utexas.tacc.tapis.jobs.worker.JobQueueProcessor.processJob(JobQueueProcessor.java:370)
>         at edu.utexas.tacc.tapis.jobs.worker.JobQueueProcessor.process(JobQueueProcessor.java:173)
>         at edu.utexas.tacc.tapis.jobs.worker.AbstractProcessor.readQueue(AbstractProcessor.java:459)
>         at edu.utexas.tacc.tapis.jobs.worker.AbstractProcessor.getNextMessage(AbstractProcessor.java:154)
>         at edu.utexas.tacc.tapis.jobs.worker.JobQueueProcessor.getNextMessage(JobQueueProcessor.java:92)
>         at edu.utexas.tacc.tapis.jobs.worker.JobWorkerThread.run(JobWorkerThread.java:64)
> Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "this._sharedAppCtxAttribs" is null
>         at edu.utexas.tacc.tapis.jobs.model.submit.JobSharedAppCtx.isSharingExecSystemId(JobSharedAppCtx.java:211)
>         at edu.utexas.tacc.tapis.jobs.model.submit.JobSharedAppCtx.getSharingExecSystemAppOwner(JobSharedAppCtx.java:214)
>         at edu.utexas.tacc.tapis.jobs.worker.execjob.JobExecutionContext.getExecutionSystem(JobExecutionContext.java:123)
>         at edu.utexas.tacc.tapis.jobs.worker.execjob.JobExecutionContext.getLogicalQueue(JobExecutionContext.java:197)
>         at edu.utexas.tacc.tapis.jobs.worker.JobQueueProcessor.validateBatchParameters(JobQueueProcessor.java:723)
>         at edu.utexas.tacc.tapis.jobs.worker.JobQueueProcessor.processJob(JobQueueProcessor.java:369)
>         ... 5 common frames omitted
>

**Comment by scblack321** [comment]
Use case is app is shared but nothing is implicitly shared. Data from the DB:
> shared_app_ctx = "wma_prtl"
> shared_app_ctx_attribs = "{}"

**Comment by scblack321** [comment]
Possibly the empty json "{}" in the DB is getting converted to a null when it should be an empty array.
See around line 3144 of edu.utexas.tacc.tapis.jobs.dao.JobsDao
> Array attribArray = rs.getArray(61);

**Comment by chandra-tacc** [comment]
Integrated from WMA and this fix works
