### ISSUE TITLE
Easy access to job directories

### ISSUE THREAD

**Issue by richcar58** [tapis-project/tapis-jobs#84]
Currently, the Jobs API supports _getJobOutputDownload_ and _getJobOutputList_ endpoints, which target the _execSystemOutputDir_.  Users have expressed interest in similar support for the _execSystemInputDir_ and _execSystemExecDir_.  One possible implementation would be to have general _getJobDownload_ and _getJobList_ endpoints that would take a _targetDirectory_ parameter with values of "Input", "Output" or "Exec".

**Comment by scblack321** [comment]
This probably came from SDSC / One Science Place.
This is probably a bad idea for security reasons. Closing for now.
